### ISSUE TITLE
Doesn't work on 1.12.2

### ISSUE THREAD

**Issue by TheLimePixel** [SilentChaos512/SilentGems#205] opened 2017-09-19 10:23 UTC
Simply, SG and SG:Extra Parts are 2 of the mods in pack that don't work on MC 1.12.2 (as you probably expected),
![image](https://user-images.githubusercontent.com/25333164/30587966-4ecabe6c-9d35-11e7-9bab-7b89965bc611.png)

**Comment by SilentChaos512** [comment] 2017-09-19 16:34
I'm surprised Forge updated so quickly. But this will probably be another effortless update for mods, like 1.12.1 was. Just need to update the version range.
Just so you're aware, the next build will likely be marked as an alpha. I'm adding new gems, so expect missing models/textures on some new blocks. Everything else should work as intended.

**Comment by TheLimePixel** [comment] 2017-09-19 17:06
Ik. I'm up-to-date with the changes.

**Closed as completed** 2017-09-19 17:25 UTC
