### ISSUE TITLE
Debugging - Minecraft 1.12.2 Forge 93

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#211] opened 2017-09-28 20:49 UTC
Missing JEI textures 
![2017-09-28 15_37_19-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/30989796-d1f2922c-a453-11e7-9491-77ffb542a961.png)
![2017-09-28 15_37_57-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/30989797-d1f49c8e-a453-11e7-8489-8d5fd06a8516.png)
![2017-09-28 15_38_21-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/30989798-d1f59b3e-a453-11e7-9c22-601647446657.png)

**Comment by P3rf3ctXZer0** [comment] 2017-09-28 20:51
jei_1.12.2-4.7.11.101.jar
SilentLib-1.12-2.2.8-88.jar
SilentsGems-1.12-2.5.1-225.jar
SGExtraParts-1.12-1.4.0-30.jar

**Comment by SilentChaos512** [comment] 2017-09-28 21:11
Duplicate of #208. Just got most of the missing textures and localizations fixed. New build should be out sometime today if all goes well.

**Closed as completed** 2017-09-29 10:06 UTC
