### ISSUE TITLE
Client Side - Tesselating block in world Crash Between Latest Silent Gems and TinkersConstruct

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#348] opened 2018-11-14 15:43 UTC
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12.2-2.8.9-306
Silent Lib Version: 1.12.2-3.0.8-158
Modpack and Version (if applicable): https://github.com/P3rf3ctXZer0/MC-ZER0PACKS/releases

### Expected behavior

- No Crashing

### Actual behaviour

- Some Crashing

### Steps to reproduce the problem

1. Log in game
2. Walk near silent gems flowers
3. ...
4. Profit

### Crash Log
https://gist.github.com/P3rf3ctXZer0/917015294ad5f1358a3b61d660484af4

### Notes - This did not start until updating the latest modpack.
[v0037.txt](https://github.com/SilentChaos512/SilentGems/files/2581434/v0037.txt)

**Comment by SilentChaos512** [comment] 2018-11-14 16:25
Looks like it's caused by a Silent Gear item on a Tinkers Construct table of some kind...? Well, I guess that's my fault for assuming other mods wouldn't access my models directly.

**Comment by P3rf3ctXZer0** [comment] 2018-11-14 16:28
Thank you for the quick response as always.

**Comment by SilentChaos512** [comment] 2018-11-17 16:29
Should be fixed in Silent Lib 3.0.9

**Closed as completed** 2019-01-17 21:45 UTC
