### ISSUE TITLE
NullPointer w/ Ardentcraft:Beginnings

### ISSUE THREAD

**Issue by TakunSho** [SilentChaos512/SilentGems#144] opened 2017-04-19 06:34 UTC
I have tried multiple versions of Silent Gems (and lib). I keep getting a nullpointer for a missing enchantment. I was getting this with both the most recent version of tinker's and the 10/22 release (had to backdate it for Tinker's Defense to work). Here is the current log file with TiCon v2.5.6b, SilentLib 1.1.0, Silent Gems 2.1.5. I have also tried using versions 2.3.8 and 2.2.5 which are also attached.
[crash-2017-04-19_02.18.02-client.txt](https://github.com/SilentChaos512/SilentGems/files/932024/crash-2017-04-19_02.18.02-client.txt) [2.2.5]
[crash-2017-04-19_01.52.49-client.txt](https://github.com/SilentChaos512/SilentGems/files/932027/crash-2017-04-19_01.52.49-client.txt) [2.3.8]
[crash-2017-04-19_02.22.11-client.txt](https://github.com/SilentChaos512/SilentGems/files/932029/crash-2017-04-19_02.22.11-client.txt) [2.1.5]

Modlist:
[modlist.txt](https://github.com/SilentChaos512/SilentGems/files/932052/modlist.txt)

**Comment by SilentChaos512** [comment] 2017-04-19 16:10
Please provide a log file as well (use latest versions of Gems/Lib). This crash is caused by an enchantment from another mod, so I would like to track it down.

**Comment by TakunSho** [comment] 2017-04-28 03:40
Here is the full log file with just ArdentCraft's 4.2.02 build and the latest Gems/Lib/Extra
[latest.log.txt](https://github.com/SilentChaos512/SilentGems/files/963383/latest.log.txt)

**Comment by SilentChaos512** [comment] 2017-04-28 04:20
Thanks. Looks like the log doesn't have the info I need though, I guess it's crashing earlier than that. I was able to replicate the crash, so I'll see what I can work out.

**Comment by SilentChaos512** [comment] 2017-04-28 04:35
Crash is caused by another mod overwriting the Sharpness enchantment (others may be affected, but can't tell at the moment). At this time, I can't say what mod is responsible. I can prevent the crash, but at worst all the "modified" enchantments will be uncraftable.

**Comment by SilentChaos512** [comment] 2017-04-30 05:37
Can you confirm if this has been fixed in Gems 2.3.11, whenever you have time?

**Closed** 2017-06-19 06:16 UTC
Labels: bug
