### ISSUE TITLE
Silent Gems and Chisel & Bits mod 1.12.2

### ISSUE THREAD

**Issue by saphsara** [SilentChaos512/SilentGems#242] opened 2017-11-18 17:25 UTC
when i try it does not allow me to chisel them with chisel and bit mod. i am using 1.12.2 . what i am tring to do is chisel a silent gem block and then put a doorbell on it..  it attempts to chisel then goes back to being whole block.

![screenshot 7](https://user-images.githubusercontent.com/33788318/32982915-d7d2f60e-cc59-11e7-98da-3e480ff7b5fe.png)

**Comment by SilentChaos512** [comment] 2017-11-18 18:23
Just installing C&B and Gems everything seems to work as intended. Did you check your Chisels & Bits config? Make sure you have the relevant blocks listed under "enabled blocks".

The config it generated for me included these:
    B:net.silentchaos512.gems.block.BlockEssenceOre=true
    B:net.silentchaos512.gems.block.BlockFluffyBlock=true
    B:net.silentchaos512.gems.block.BlockGem=true
    B:net.silentchaos512.gems.block.BlockGemBrick=true
    B:net.silentchaos512.gems.block.BlockGemLamp=true
    B:net.silentchaos512.gems.block.BlockGemOre=true
    B:net.silentchaos512.gems.block.BlockMisc=true

**Comment by saphsara** [comment] 2017-11-18 19:12
sweet thank thats what i needed, i didnt know how to add it and what to add... awesome ty

**Comment by saphsara** [comment] 2017-11-18 20:09
I added that info and restarted server and game.. i am still unable to use chisel and bits .

**Comment by SilentChaos512** [comment] 2017-11-18 20:11
Sorry, I assumed the issue was fixed based on your previous comment. Did you update the config on both the client and server?

**Comment by saphsara** [comment] 2017-11-18 20:18
thats ok . thought that would fix it . my fault. yes, i did. added it to both configs , made sure i have the newest mod and lib and restarted server and game. checked the configs and the info is in there

**Comment by SilentChaos512** [comment] 2017-11-18 20:23
Could I see a full server log, please? Upload it to another site like Gist or Pastebin, then give me the link.

**Comment by saphsara** [comment] 2017-11-18 20:26
share link from my one drive..  only way i know how to  https://1drv.ms/u/s!AtL7UzgcOoZ3snuwYAtZn3X0tD5x

**Comment by saphsara** [comment] 2017-11-18 20:27
is that what you are looking for?

**Comment by SilentChaos512** [comment] 2017-11-18 20:41
Not really seeing anything useful there, but I'm not sure what I'm looking for either. Do you have any issues on singleplayer? What you originally described sounds like some kind of communication error between client and server.

**Comment by saphsara** [comment] 2017-11-18 20:48
I tried single player and it works. i am going to reinstall game. maybe that will work.

**Comment by saphsara** [comment] 2017-11-18 21:36
single player works and i still cant get multi player to work

**Comment by saphsara** [comment] 2017-11-19 00:13
here is the error 
[00:12:13] [Server thread/INFO] [chiselsandbits]: Unable to determine blocks eligibility for chiseling, net.silentchaos512.lib.block.BlockSL attempted to load net/minecraft/client/util/ITooltipFlag

[00:12:13] [Server thread/INFO] [chiselsandbits]: Unable to determine blocks eligibility for chiseling, net.silentchaos512.lib.block.BlockSL attempted to load net/minecraft/client/util/ITooltipFlag

[00:12:13] [Server thread/INFO] [chiselsandbits]: Unable to determine blocks eligibility for chiseling, net.silentchaos512.lib.block.BlockSL attempted to load net/minecraft/client/util/ITooltipFlag

[00:12:13] [Server thread/INFO] [chiselsandbits]: Unable to determine blocks eligibility for chiseling, net.silentchaos512.lib.block.BlockSL attempted to load net/minecraft/client/util/ITooltipFlag

[00:12:13] [Server thread/INFO] [chiselsandbits]: Unable to determine blocks eligibility for chiseling, net.silentchaos512.lib.block.BlockSL attempted to load net/minecraft/client/util/ITooltipFlag

[00:12:13] [Server thread/INFO] [chiselsandbits]: Unable to determine blocks eligibility for chiseling, net.silentchaos512.lib.block.BlockSL attempted to load net/minecraft/client/util/ITooltipFlag

[00:12:18] [Server thread/INFO]: saphsara lost connection: Disconnected

[00:12:18] [Server thread/INFO]: saphsara left the game

**Comment by SilentChaos512** [comment] 2017-11-19 00:19
That's a good clue. I'll take a look when I get home from work.

**Comment by saphsara** [comment] 2017-11-19 00:27
ok thank, i also tried recreating server on another ip address from scratch new world new files. same thing. 
thank you for all your help.

**Comment by SilentChaos512** [comment] 2017-11-19 06:07
Fixed by a small Silent Lib update. No update for Gems needed. I'll upload the new version now.

**Closed as completed** 2017-11-19 06:06 UTC

**Comment by saphsara** [comment] 2017-11-19 15:48
It works, It works. Thank you! You are awesome!!!!!!
