### ISSUE TITLE
Issues with renderer

### ISSUE THREAD

**Issue by DPxKnightxZero** [SilentChaos512/SilentGems#8] opened 2016-01-22 08:55 UTC
Error -> https://gist.github.com/DPxKnightxZero/4d51845faf110ee8ddc5

**Comment by SilentChaos512** [comment] 2016-02-10 18:29
Server-side log output caused by a "fake" item trying to use client-side stuff. On 1.7.10, this does not cause an issue to my knowledge (correct me if I'm wrong), just the log output. This was fixed on 1.8.x because it did crash.

Not worth fixing just to remove log output. I hope I don't sound rude, that's not my intention.

**Closed by SilentChaos512** 2016-02-10 18:29 UTC
Labels: wontfix

**Comment by P3rf3ctXZer0** [comment] 2016-11-15 22:44
Its console spamming that is the issue which drops FPS to almost nothing.

**Comment by SilentChaos512** [comment] 2016-11-15 22:47
This issue is so old I don't even remember what the problem was. If you are having problems with a recent version, please make a new issue.
