### ISSUE TITLE
at net.silentchaos512.gems.chaos.ChaosHandler.onLivingUpdate(ChaosHandler.java:47)

### ISSUE THREAD

**Issue by MSandro** [SilentChaos512/SilentGems#367] opened 2019-04-27 15:56 UTC
### Versions
SilentGems-1.13.2-3.0.12+28.jar
SilentLib-1.13.2-4.0.8+23.jar
Forge 25.0.175
MC 1.13.2

### Expected behavior
loading the world and be able to play!

### Actual behaviour
MC started up as expacted but I can't create a world. I shortly see the world and then it crashes.

### Crash Log

```
---- Minecraft Crash Report ----
// You're mean.

Time: 4/27/19 5:51 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:103)
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:119)
	at net.minecraft.entity.EntityLivingBase.getCapability(EntityLivingBase.java:2482)
	at net.minecraft.entity.player.EntityPlayer.getCapability(EntityPlayer.java:2151)
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48)
	at net.silentchaos512.gems.chaos.ChaosHandler.onLivingUpdate(ChaosHandler.java:47)
	at net.minecraftforge.eventbus.ASMEventHandler_172_ChaosHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1715)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:219)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:350)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:178)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:115)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:103)
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:119)
	at net.minecraft.entity.EntityLivingBase.getCapability(EntityLivingBase.java:2482)
	at net.minecraft.entity.player.EntityPlayer.getCapability(EntityPlayer.java:2151)
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48)
	at net.silentchaos512.gems.chaos.ChaosHandler.onLivingUpdate(ChaosHandler.java:47)
	at net.minecraftforge.eventbus.ASMEventHandler_172_ChaosHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1715)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:219)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 309
	Entity Name: MSandro
	Entity's Exact location: 222.50, 63.00, -199.50
	Entity's Block location: World: (222,63,-200), Chunk: (at 14,3,8 in 13,-13; contains blocks 208,0,-208 to 223,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:350)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:178)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@5627f20b
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:115)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 662727320 bytes (632 MB) / 2717908992 bytes (2592 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m -XX:PermSize=256m
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['MSandro'/309, l='1', x=222.50, y=63.00, z=-199.50]]
	Data Packs: vanilla, mod:simplesponge, mod:simplegrinder, mod:silentlib, mod:silentgems, mod:silentgear, mod:forge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by SilentChaos512** [comment] 2019-04-27 16:01
Duplicate of #361. This crash is caused by another mod handling capabilities incorrectly, nothing I can do to fix it. Right now, process of elimination is the only way to find the mod responsible. Forge is supposed to make a change to point to the right mod, but I guess that still hasn't gone through.

**Closed as completed** 2019-07-25 16:47 UTC
Labels: third party issue, 1.13
