### ISSUE TITLE
Chaos Note - Ticking Block Entity Crash

### ISSUE THREAD

**Issue by rsfuja** [SilentChaos512/SilentGems#228] opened 2017-11-07 18:07 UTC
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.5.9-245
Silent Lib Version: 1.12-2.2.11-92

### Actual behaviour

Game crash when nodes attack (or kill) entities?    

[crash-2017-11-07_12.09.10-server.txt](https://github.com/SilentChaos512/SilentGems/files/1451118/crash-2017-11-07_12.09.10-server.txt)

**Comment by SilentChaos512** [comment] 2017-11-08 05:06
Can't reproduce this, even will all the Team CoFH mods installed. Not sure why this is even getting passed to a CoFH Core class. But I have an idea for a workaround.

**Comment by SilentChaos512** [comment] 2017-11-08 21:19
Should be fixed in 2.5.10. Re-open if you still crash.

**Closed as completed by SilentChaos512** 2017-11-08 21:19 UTC
Labels: bug
