### ISSUE TITLE
1.19.4 not generating anything.

### ISSUE THREAD

**Issue by HDD-Neptunia** [SilentChaos512/SilentGems#578] opened 2023-07-11 21:07 UTC
Version 1.19.4

- **Silent's Gems**: 
- **Silent Gear**: N/A 
- **Silent Lib**: 4.4.2 and 4.5.0
- **Forge**: 45.1.0/1.2  (I did try multiple,  to no avail)
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
World gen to function correctly

## Actual Behavior
I understand this has been listed once, but I want to point out that the glow roses aren't generating either. I hope this helps in some way or another. The ores are all in JEI, but only the bort ore is actually spawning

## Steps to Reproduce the Problem

1. I've even tried a fresh install. I only have your mods installed, so it should be easy to replicate.
2. 
3. Thank you for the awesome mod! I actually can't play without it haha

**Comment by CORRUPTEDUSER404** [comment] 2023-07-17 06:31
Interesting, I didn't notice that. I guess that that is also broken.

**Comment by HDD-Neptunia** [comment] 2023-07-17 17:13
> Interesting, I didn't notice that. I guess that that is also broken.

I thought adding some of my findings might assist. I know 1.19.4 is a bit borked

I hate to do this here, but I really like your work. I'm learning to mod, myself. I was wondering if you have any advice with learning the forge libraries? 
Thank you! I hope you have a nice day

**Comment by CORRUPTEDUSER404** [comment] 2023-07-17 20:23
Umm. Im not apart of the mod. Im just having the same isues

**Comment by lekonai** [comment] 2023-07-19 20:01
having the same issue aquí!

**Comment by SilentChaos512** [comment] 2023-08-11 15:00
Duplicate of #577

**Closed as completed by SilentChaos512** 2023-08-11 15:00 UTC
Labels: bug
