### ISSUE TITLE
Messed up texture?

### ISSUE THREAD

**Issue by BSKCorp** [SilentChaos512/SilentGems#68] opened 2016-09-21 23:40 UTC
Silent Gems - 1.10.2-2.0.30-70
Forge 1.10.2-12.18.1.2088

Updated to this version now the Beryl-Opal Sword is.. looking rather strange. 

http://imgur.com/T7AjkX7

Is this on purpose? lol thanks in advanced sorry to bother you about this.

**Comment by SilentChaos512** [comment] 2016-09-21 23:44
Duplicate of #63. It's a side effect of new part models being added. Place the tool in a crafting grid to fix it. Any tools in your inventory are automatically updated, ones in chests/item frames can get scrambled.

**Closed by SilentChaos512** 2016-09-21 23:44 UTC
