### ISSUE TITLE
Chaos repairing my items (that have durability)

### ISSUE THREAD

**Issue by S10MC2015** [SilentChaos512/SilentGems#194] opened 2017-08-04 17:03 UTC
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.4.3
Silent Lib Version: 2.2.6

### Actual behaviour

- Chaos repairing my bow

### Steps to reproduce the problem

1. Get a damaged bow from somewhere
2. (not sure if needed) have a chaos orb and chaos gem on you
3. Have chaos nodes by you (you may need more than one)
4. Profit

**Comment by SilentChaos512** [comment] 2017-08-04 17:14
This is a feature of chaos nodes, not a bug. The blue "packets" repair damaged items. But thanks for reporting.

**Comment by S10MC2015** [comment] 2017-08-04 17:16
You may want to make it not repair other mods op items like draconic armor

**Comment by SilentChaos512** [comment] 2017-08-04 17:18
I'm not too familiar with Draconic Evolution, I'll take a look into that. Maybe add a repair blacklist.

**Comment by S10MC2015** [comment] 2017-08-04 17:20
ok

**Comment by SilentChaos512** [comment] 2017-09-16 19:59
Added a repair blacklist and whitelist, closed by 22d3aee7d515da0202f7d30d6108b29f1c555c5d.

**Closed as completed by SilentChaos512** 2017-09-16 19:59 UTC
