### ISSUE TITLE
Unable to craft the Upgrade Base

### ISSUE THREAD

**Issue by Keaton1188** [SilentChaos512/SilentGems#247] opened 2017-11-24 00:18 UTC
Hi there, we are having an issue where you can't craft the Upgrade Base, a player is telling me its just 1 stick and 1 wood plank.. I wouldn't know as in the NEI it doesn't show a recipe for it..

Minecraft version: 1.12.2

Silent Gems: SilentsGems-1.12-2.5.10-247.jar
Silent Lib: SilentLib-1.12-2.2.12-93.jar

**Comment by SilentChaos512** [comment] 2017-11-24 01:26
Duplicate of #230 and #243. This is fixed in 2.5.11 and 2.6.1.

**Closed as completed** 2017-11-24 07:52 UTC
Labels: duplicate
