### ISSUE TITLE
Tip Upgrade in Horizons III not working

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/SilentGems#244] opened 2017-11-20 03:47 UTC
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.10-247
Silent Lib Version: 2.2.12-93
Modpack and Version (if applicable): Horizons III 1.2.1

### Expected behavior

- Apply a tip upgrade to a tool and get an upgraded tool.

### Actual behaviour

- Tool staying exactly and no adjustment other than visual being made to the tool

### Steps to reproduce the problem

1. Craft a regular pick out of gems. Any gems were doing it.
2. Craft a diamond tip upgrade and apply it to the tool

I have tried different types of tip upgrades to different types of tools. All seem to be currently failing. I'm new to this mod, but before the last update to Horizons I had upgraded my flint tools with iron upgrades so it had been working, but now only makes visual changes.

**Comment by SilentChaos512** [comment] 2017-11-20 05:45
Duplicate of #235. This has been fixed in versions 2.5.11 and 2.6.1. I'll leave this issue open until Horizons III updates.

**Closed as completed** 2018-01-03 06:23 UTC
Labels: duplicate, already fixed
