### ISSUE TITLE
[Crash] [Critical] Server crash when a node tries to apply the repair effect

### ISSUE THREAD

**Issue by MysticAura** [SilentChaos512/SilentGems#75] opened 2016-11-10 17:02 UTC
MC Version: 1.10.2
Forge Version: 2121
Mod Version: 2.1.1

[Crash Log](http://pastebin.com/6sgiAZNd)

Happens every time. Edit: Also happens with levitation effect.

**Comment by SilentChaos512** [comment] 2016-11-10 22:17
Duplicate of #74. Happens with all chaos node packet entities, will be fixed in the next update (probably today or tomorrow).

**Closed by SilentChaos512** 2016-11-10 22:17 UTC
