### ISSUE TITLE
1.11.2 [Crash] Enchant Tokens (Survival & Creative)

### ISSUE THREAD

**Issue by Slither88** [SilentChaos512/SilentGems#112] opened 2017-01-27 08:14 UTC
I get a crash with a small custom mod collection that I put together. The crash happens when i try to open the creative tab that contains the enchantment tokens. After the crash if I try to go back into the world it just crashes again. This might be another mods enchants making a mess, but I know that there was an issue with your token before so just in case. Below is the crash report.

I have tested it in survival as well and all the enchantment tokens show up through JEI without issue, but I  do see that there seems to be two "blank" spots among the tokens. It also only stays stable for a small bit and ends up crashing anyway. Logs below as well.

I am using  SilentsGems-1.11-2.2.7-110 and SilentLib-1.11-1.2.0-30, the latest versions on curseforge with the latest version of forge 30.20.0.2226.

Logs:

Creative
http://pastebin.com/4weWCcki

Survival:
http://pastebin.com/7yyFykwW

**Comment by SilentChaos512** [comment] 2017-01-27 18:48
This is a duplicate of #109. It's caused by a mod doing something weird with an enchantment (null type). The crash is fixed for the next version.

Thanks for the second crash report, it mentions the enchantment is "adinferos:curse_protection". So I'm guessing [this mod](https://minecraft.curseforge.com/projects/ad-inferos) is responsible. It's probably not something they need to be warned about, but it's nice to know what I need to test.

**Closed** 2017-01-29 06:40 UTC
