### ISSUE TITLE
Issue crafting an upgrade base since server update

### ISSUE THREAD

**Issue by pianoninja247** [SilentChaos512/SilentGems#243] opened 2017-11-18 18:35 UTC
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.10
Silent Lib Version: 2.2.12
Modpack and Version (if applicable): Horizons III 1.2.1

### Expected behavior

Crafting with 2 flint, 1 stick and 1 plank is supposed to produce an "upgrade base"

### Actual behaviour

Unable to craft it with given recipe. JEI won't even pull up the information on how to craft it.
Trying to look at the recipe of ones previously crafted will kick players from the server.

### Help please!
Anyone else having this issue? Or tips to solve it if the issue is with our server and not the mod?

**Comment by SilentChaos512** [comment] 2017-11-18 18:44
Duplicate of #230. This has been fixed in versions 2.5.11 and 2.6.1. I'll leave this open until Horizons III fixes the issue.

**Closed as completed** 2018-01-03 06:23 UTC
Labels: duplicate, already fixed
