### ISSUE TITLE
Enriched Chaos Essence Recipe Broken

### ISSUE THREAD

**Issue by Doublebass91** [SilentChaos512/SilentGems#234] opened 2017-11-12 19:16 UTC
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.5.10-247
Silent Lib Version: 1.4.1-34

### Expected behavior

- Crafting Enriched Chaos Essence.

### Actual behaviour

- Recipe for enriched chaos essence actually crafts Chaos Essence Block.

### Steps to reproduce the problem

Attempt to craft Enriched Chaos Essence

![enriched chaos problem](https://user-images.githubusercontent.com/27504635/32702342-cbefd604-c7b3-11e7-8b13-ef5eef97f3c2.png)

**Comment by SilentChaos512** [comment] 2017-11-12 19:20
I'm not seeing this. Can you reproduce the problem with a clean instance and nothing but Gems/Lib installed?

**Comment by Doublebass91** [comment] 2017-11-12 19:25
I don't Believe i can , This is using Your mod as part of Horizons 3 Pack. this among numerous other bugs within the mod are cropping up Ever since updating the server i run to the latest version for Horizons 3 "1.2". So it must be some conflict with Something that was updated. Should have Said it was part of that pack my apologies.

**Comment by chrixian** [comment] 2017-11-14 12:06
I'm also experiencing this issue on Horizons III-- Oddly though, if you use 1 of each item in the recipe (rather than stacks like in the picture above) the recipe works ... it seems like if it finds 9 or more chaos essence total, the block recipe gets used ... But I'm also unable to craft Upgrade Bases and if I cheat them in and create an upgrade Tip they have no effect when applied to a tool ... (Dunno if those are the 'other bugs' @Doublebass91 was referring to but those are the ones I'm experiencing)

**Comment by SilentChaos512** [comment] 2017-11-14 19:46
@chrixian Upgrade base and tipped upgrade issues have been reported (#230, #235) and are fixed for the next build.

**Comment by cScotPlay** [comment] 2017-11-18 08:32
I have also run into this issue when trying to craft multiple chaos essence. Except I was not on Horizons III instead I was on Mech & Magic ver 1.12.2. I was also allowed for single item crafting but when presented with more than one item

**Comment by CharCharthemonkey** [comment] 2017-11-24 04:10
im also getting this issue in my modpack (custom 1.12.2 pack) where shift clicking any Silents gems items makes the essence block instead of the requested item

**Comment by SilentChaos512** [comment] 2017-11-25 18:12
My best guess is that some mod is trying to be clever (and failing) by allowing you to craft blocks using the recipe for the item the blocks are made up, but it's not considering metadata. The hard part is figuring out what that mod is. Does it sound familiar to anyone?

**Comment by CharCharthemonkey** [comment] 2017-11-26 04:11
easiest way would be comparing mod lists between horizons 3 and my custom pack since i get the same bug any mods matching would have to be put in a new pack to test and ID the broken mod

**Comment by Quostin** [comment] 2017-11-27 22:12
1.12.2 of Mech & Magic is also having this problem. If you do the recipe without any extra essences, you can make it, but as soon as you go over 8, it makes a block.

![image](https://user-images.githubusercontent.com/13752478/33294693-c1af580c-d39f-11e7-9527-762a7bc1fa6a.png)

It not just Chaos blocks. Anything that fills the whole table can turn into a block.

**Comment by SilentChaos512** [comment] 2017-12-02 22:32
@Quostin What Mech & Magic version? Everything seems normal in RC5.

**Comment by Y0ungSandwich** [comment] 2017-12-02 22:34
@SilentChaos512 This was in RC4 with the issue with cyclic. Its fixed now as we are using the beta version of cyclic that fixes it.

**Closed as completed** 2018-06-29 01:58 UTC
