### ISSUE TITLE
Shift Clicking with a non super tier sword causes a "fatal error"

### ISSUE THREAD

**Issue by EtherG** [SilentChaos512/SilentGems#179] opened 2017-07-14 12:39 UTC
Playing on a server
SilentGems-1.12-2.4.2-206
SilentLib-1.12-2.2.6-83

Nothing in console other than a java error one time i tested it. Probably nothing of importance.
https://paste.ee/p/Sw7wu

**Comment by SilentChaos512** [comment] 2017-07-16 17:34
Does this happen consistently for you? I don't get any errors like this.

**Comment by Kris1432** [comment] 2017-07-16 18:20
@SilentChaos512 have you tried serverside at all?

**Comment by FridgeBoy** [comment] 2017-07-16 18:26
Completely consistent
made a quick video to demonstrate, nothing particular relating to it is in the logs either
https://www.youtube.com/watch?v=nC-OW2gNYdk
Edit: Uploaded to youtube instead of google drive

**Comment by Kris1432** [comment] 2017-07-16 18:29
I can provide anything from the server if needed.

**Comment by SilentChaos512** [comment] 2017-07-16 18:55
I did try this on a server, yes. 1.12 dev environment with very few other
mods installed. Likely a mod interaction, so I'll need a full mod list at
the very least. Client/server logs might be helpful.

**Comment by Kris1432** [comment] 2017-07-18 22:43
Modlist: https://pastebin.com/s4RZDcfK

Latest Log: https://pastebin.com/1cDL5U1P

FML-Server-Latest Log: https://pastebin.com/v5wUpQkf

**Comment by SilentChaos512** [comment] 2017-07-24 15:27
~~Sorry I haven't had any time to look into this. What needs to be done (if anyone would be so kind as to help) is to figure out if another mod is interacting badly with Gems. Set up a temporary server with the given modlist, and remove half the mods. If the error still exists, repeat for the by cutting the mods in half again. Otherwise, repeat for the half that was removed. Continue until you can determine which mod the error occurs with.~~

~~As it is right now, I don't have enough information to determine what the problem is.~~

OK, got it to produce the error this time, and it produced some helpful output. I should have a fix now.

**Comment by EtherG** [comment] 2017-07-24 16:02
https://pastebin.com/mBmRPRWY server side console says this, seems to be a problem with the chaos gui

**Comment by SilentChaos512** [comment] 2017-07-24 16:03
Yeah, that's what I just found. The condition for when to display the GUI was wrong, and it was trying to show it on the server side in some cases.

**Comment by SilentChaos512** [comment] 2017-07-24 16:19
Uploading 2.4.3b build. Update servers, clients shouldn't _need_ to update, but I would.

**Comment by EtherG** [comment] 2017-07-24 16:26
Thanks

**Comment by Kris1432** [comment] 2017-07-25 09:07
@SilentChaos512 I will update our server tonight and get test it out and then try to get this issue closed.

**Comment by Kris1432** [comment] 2017-07-26 15:53
All fixed on our end, feel free to close this!

**Comment by SilentChaos512** [comment] 2017-07-26 19:20
Great, good to hear.

**Closed as completed by SilentChaos512** 2017-07-26 19:20 UTC
Labels: bug
