### ISSUE TITLE
[1.13.2] java.lang.IllegalStateException: Cannot build unresolved tag entry (crash on world load)

### ISSUE THREAD

**Issue by SDUBZ** [SilentChaos512/SilentGems#366] opened 2019-04-17 07:20 UTC
- **Silent's Gear**: SilentGear-1.13.2-1.0.8+18
- **Silent's Gems**: 1.13.2-3.0.11+26
- **Silent Lib**: 1.13.2-4.0.7+20
- **Forge**: 1.13.2-146
- **Modpack** (if applicable): Custom

### Expected behavior
Game to load with no issues

### Actual behaviour
Game crashes on world load/creation

### Links/Images

- 
logs:
[latest (2).txt](https://github.com/SilentChaos512/SilentGems/files/3088300/latest.2.txt)

crash report:
[crash-2019-04-17_17.13.34-server.txt](https://github.com/SilentChaos512/SilentGems/files/3088302/crash-2019-04-17_17.13.34-server.txt)

### Steps to reproduce the problem

1.Load with stated forge and mods
2.Reach main menu and join/create world
3.Crash

**Comment by SilentChaos512** [comment] 2019-04-17 14:55
I've seen this before, think it's caused by a mod conflict, but no idea why. If you added any mods recently, try removing them. If you can find a single mod that seems to cause this, please let me know which it is. That might give a clue about what is going wrong. I'll do some more research when I have time.

**Comment by SDUBZ** [comment] 2019-04-24 22:37
Tested so far
just a few more ores mod
forbidden and arcanus mod(This i think has relation to what ever you doing with blocks in silent gems)
koratio mod

Still crashes on world with new silent gear and newer forge

crash:
[crash-2019-04-25_08.55.07-server.txt](https://github.com/SilentChaos512/SilentGems/files/3114455/crash-2019-04-25_08.55.07-server.txt)

logs:
[debug.log.txt](https://github.com/SilentChaos512/SilentGems/files/3114456/debug.log.txt)


[latest.log.txt](https://github.com/SilentChaos512/SilentGems/files/3114458/latest.log.txt)

**Comment by SDUBZ** [comment] 2019-04-29 05:05
think i found a conflict with trap expansion mod or its dependency lemonlib 
Another conflict is inventory generators it seems

**Comment by SilentChaos512** [comment] 2019-04-29 14:49
I forgot to mention, but Gems 3.0.12 has a potential fix for this issue, have you tried it?

Trap Expansion and LemonLib seem to be causing the "null capability" crash (like #361 and #367). Inventory Generators seems fine.

**Comment by SDUBZ** [comment] 2019-05-02 22:59
i will give try later today

**Comment by SDUBZ** [comment] 2019-05-14 04:49
seems like biggest conflict is silent gems/gears and mubble mod 
[debug.log](https://github.com/SilentChaos512/SilentGems/files/3175873/debug.log)
if thats what im getting from this log

**Closed as completed** 2019-07-25 16:48 UTC
Labels: 1.13
