### ISSUE TITLE
Server crash that mentions Selim's enchants and Silent gems

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/SilentGems#356] opened 2019-03-01 08:41 UTC
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: SilentsGems-1.12.2-2.8.15+316
Silent Lib Version: SilentLib-1.12.2-3.0.13+167
Modpack and Version (if applicable): Transcendence 0.2.0

### Expected behavior

- That it'll load.

### Actual behaviour

- it did this.

### Steps to reproduce the problem

Load it. it blows up.

in all seriousness and premade formats aside, I was just attempted to update my server with my latest transcendence version at long last. but this happens. Versions mentioned are there. And selims is this version: Selim's Enchantments-1.12.2-2.1.0

around half way through multicraft would just restart the loading, meaning something crashed. grabbed the crash log out of the server and this is what I got. I'll be sending it to both sides and linking the two issues, hopefully you's can work it all out. :) it mentions the enchantment tokens, so probably something to do with that. 

heres the log:

https://pastebin.com/WB2cqXUk

Selim's Side:
https://github.com/Selim042/SM-Selim-Enchants/issues/7

**Comment by SilentChaos512** [comment] 2019-03-01 14:36
Looks like a duplicate of #343. Commented on Selim's issue. Seems the previous fix was never released, unless I'm misreading something.

**Closed as completed** 2019-03-05 14:37 UTC
Labels: duplicate, 1.12
